baseURL = "https://zhangyi999.github.io/docs-3/"
canonifyURLs = true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "./themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"

[outputs]
home = [ "HTML", "RSS", "JSON"]


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo Learn Theme"
# weight = 2
# languageName = "English"


# [Languages.fr]
# title = "Documentation du thème Hugo Learn"
# weight = 2
# languageName = "Français"


